In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
url = "https://raw.githubusercontent.com/guille1006/TFM/refs/heads/main/data/raw_data.csv"
df = pd.read_csv(url)

<table>
  <tr><th>Campo</th><th>Variable valida</th><th>Tipo</th><th>Descripción</th></tr>
  
  <tr><td colspan="4" align="center"><b> Dirección del inmueble</b></td></tr>
  <tr><td>latitude</td><td>Si</td><td>float</td><td>Coordenada de latitud</td></tr>
  <tr><td>longitude</td><td>Si</td><td>float</td><td>Coordenada de longitud</td></tr>
  <tr><td>showAddress</td><td>Si</td><td>bool</td><td>Muestra la dirección o no</td></tr>
  <tr><td>address</td><td>Si</td><td>category</td><td>Calle, número y país del inmueble</td></tr>
  <tr><td>neighborhood</td><td>Si</td><td>category</td><td>Vecindario donde está ubicado el inmueble</td></tr>
  <tr><td>district</td><td>Si</td><td>category</td><td>Distrito donde está ubicado el inmueble</td></tr>
  <tr><td>municipality</td><td>Si</td><td>category</td><td>Municipio donde está ubicado el inmueble</td></tr>
  <tr><td>province</td><td>Si</td><td>category</td><td>Provincia donde está ubicado el inmueble</td></tr>
  <tr><td>country</td><td>Si</td><td>category</td><td>País donde está ubicado el inmueble</td></tr>

  <tr><td colspan="4" align="center"><b> Características propias del inmueble</b></td></tr>
  <tr><td>rooms</td><td>Si</td><td>int</td><td>Número de habitaciones del inmueble</td></tr>
  <tr><td>size</td><td>Si</td><td>float</td><td>Metros cuadrados del inmueble</td></tr>
  <tr><td>bathrooms</td><td>Si</td><td>int</td><td>Número de baños</td></tr>
  <tr><td>exterior</td><td>Si</td><td>bool</td><td>Tiene parte exterior o no</td></tr>
  <tr><td>status</td><td>Si</td><td>category</td><td>Estado de la vivienda</td></tr>
  <tr><td>detailedType.subTypology</td><td>Si</td><td>category</td><td>Subtipo de inmueble</td></tr>
  <tr><td>detailedType.typology</td><td>Si</td><td>category</td><td>Tipo de inmueble</td></tr>
  <tr><td>floor</td><td>Si</td><td>int</td><td>Altura del piso</td></tr>
  <tr><td>hasLift</td><td>Si</td><td>bool</td><td>Tiene ascensor o no</td></tr>
  <tr><td>parkingSpace.hasParkingSpace</td><td>Si</td><td>bool</td><td>Tiene espacio para aparcar o no</td></tr>
  <tr><td>parkingSpace.isParkingSpaceIncludedInPrice</td><td>Si</td><td>bool</td><td>Está el precio del aparcamiento incluido en el precio o no</td></tr>
  <tr><td>parkingSpace.parkingSpacePrice</td><td>Si</td><td>float</td><td>Precio del espacio de aparcamiento</td></tr>
  <tr><td>price</td><td>Si</td><td>float</td><td>Precio del inmueble</td></tr>
  <tr><td>priceInfo.price.amount</td><td>Si</td><td>float</td><td>Precio del inmueble</td></tr>
  <tr><td>priceByArea</td><td>Si</td><td>float</td><td>Precio del metro cuadrado del inmueble</td></tr>
  <tr><td>priceInfo.price.currencySuffix</td><td>Si</td><td>category</td><td>Moneda del precio</td></tr>
  <tr><td>priceInfo.price.priceDropInfo.formerPrice</td><td>Si</td><td>float</td><td>Precio anterior del inmueble</td></tr>
  <tr><td>priceInfo.price.priceDropInfo.priceDropPercentage</td><td>Si</td><td>float</td><td>Porcentaje de rebaja del precio con respecto al precio anterior</td></tr>
  <tr><td>priceInfo.price.priceDropInfo.priceDropValue</td><td>Si</td><td>float</td><td>Cantidad del dinero que se ha rebajado con respecto al precio anterior</td></tr>
  <tr><td>newDevelopment</td><td>Si</td><td>bool</td><td>Es vivienda de nueva construcción o no</td></tr>
  <tr><td>newDevelopmentFinished</td><td>Si</td><td>bool</td><td>Es vivienda de nueva construcción terminada o no</td></tr>
  <tr><td>topNewDevelopment</td><td>Si</td><td>bool</td><td>Es un inmueble de nueva construcción o no</td></tr>
  <tr><td>highlight.groupDescription</td><td>Si</td><td>category</td><td></td></tr>

  <tr><td colspan="4" align="center"><b> Información relacionada con el anuncio</b></td></tr>
  <tr><td>description</td><td>Si</td><td>category</td><td>Descripción del anuncio, escrita por el dueño o la inmobiliaria</td></tr>
  <tr><td>numPhotos</td><td>Si</td><td>int</td><td>Número de fotos</td></tr>
  <tr><td>has360</td><td>Si</td><td>bool</td><td>Tiene imagen 360º del piso o no</td></tr>
  <tr><td>has3DTour</td><td>Si</td><td>bool</td><td>Tiene tour 3D o no</td></tr>
  <tr><td>hasVideo</td><td>Si</td><td>bool</td><td>Tiene video o no</td></tr>
  <tr><td>hasPlan</td><td>Si</td><td>bool</td><td>Tiene vista en plano o no</td></tr>
  <tr><td>hasStaging</td><td>Si</td><td>bool</td><td>Tiene visualización HomeStaging o no</td></tr>
  <tr><td>operation</td><td>Si</td><td>category</td><td>Tipo de operación: Venta, alquiler...</td></tr>
  <tr><td>suggestedTexts.subtitle</td><td>Si</td><td>object</td><td>Subtítulo del anuncio</td></tr>
  <tr><td>suggestedTexts.title</td><td>Si</td><td>object</td><td>Título del anuncio</td></tr>

  <tr><td colspan="4" align="center"><b> Información propia de Idealista</b></td></tr>
  <tr><td>externalReference</td><td>Si</td><td>object</td><td>Referencia externa usada por la página web de Idealista</td></tr>
  <tr><td>thumbnail</td><td>Si</td><td>object</td><td>Enlace a una imagen del anuncio</td></tr>
  <tr><td>topPlus</td><td>Si</td><td>bool</td><td>Pertenece al plan Plus o no</td></tr>
  <tr><td>highlight.groupDescription</td><td>Si</td><td>category</td><td>Tipo de grupo de descripcion</td></tr>
  <tr><td>url</td><td>Si</td><td>object</td><td>URL del anuncio</td></tr>
  <tr><td>notes</td><td>No</td><td>list</td><td>Lista vacía, no sabemos su uso</td></tr>
</table>


### Explicación de las variables no usadas:
* url: url para acceder al anuncio, no tiene sentido usarla en un modelo predictivo
* externalReference: Tampoco tiene sentido usarla en un modelo predictivo
* thumbnail: es simplemente una imagen
* notes: Es siempre una lista vacía
* Country, province: Estamos siempre usando Madrid, con lo que el valor es el mismo
* operation: Siempre usamos viviendas que estan en venta
* priceInfo.price.currencySuffix: Todas usan como moneda el euro
* TopNewDevelopment: El valor es Nulo o falso

In [3]:
var = "notes"
print(df[var].nunique())
df[var]

1

0        []
1        []
2        []
3        []
4        []
         ..
17456    []
17457    []
17458    []
17459    []
17460    []
Name: notes, Length: 17461, dtype: object

In [12]:
df_copy = df.copy()

In [13]:
# Columnas que no son necesarias para la limpieza de datos inicial
cols_to_drop = [
    'url', 'externalReference', 'thumbnail', 'propertyCode', 
    'description', 'suggestedTexts.title', 'suggestedTexts.subtitle',
    'notes', 'address', 'country', 'province', 'operation', 'priceInfo.price.currencySuffix',
    'topNewDevelopment', 'latitude', 'longitude'
]

df_copy.drop(columns=cols_to_drop, inplace=True)

column_tot = len(df_copy.columns)

# Voy a realizar un estudio de las variables y del tipo de estas
info_types = pd.DataFrame(
    {"Tipo de columna": df_copy.dtypes, 
     "Valores únicos": df_copy.nunique(dropna=False),
     "Valores nulos": df_copy.isnull().sum()}
).sort_values(by="Valores nulos", ascending=False)

info_types

,Tipo de columna,Valores únicos,Valores nulos
parkingSpace.parkingSpacePrice,float64,58,17192
priceInfo.price.priceDropInfo.priceDropValue,float64,220,15687
priceInfo.price.priceDropInfo.formerPrice,float64,635,15687
priceInfo.price.priceDropInfo.priceDropPercentage,float64,25,15687
newDevelopmentFinished,object,3,15678
detailedType.subTypology,object,14,11193
highlight.groupDescription,object,4,10813
parkingSpace.hasParkingSpace,object,2,9617
parkingSpace.isParkingSpaceIncludedInPrice,object,3,9617
neighborhood,object,196,6979
floor,object,41,5028
exterior,object,3,4944
hasLift,object,3,4668
district,object,271,2429
status,object,4,385
size,float64,889,0
showAddress,bool,2,0
rooms,int64,21,0
priceByArea,float64,7061,0
priceInfo.price.amount,float64,2811,0
propertyType,object,6,0
bathrooms,int64,18,0
price,float64,2811,0
numPhotos,int64,142,0
newDevelopment,bool,2,0
municipality,object,178,0
hasVideo,bool,2,0
hasStaging,bool,2,0
hasPlan,bool,2,0
has3DTour,bool,2,0
has360,bool,2,0
detailedType.typology,object,3,0
topPlus,bool,2,0

In [ ]:
def tabla_valores_unicos(df):
    df_frec = pd.DataFrame()

    for col in df.columns:
        # generare, solo para la visualización que estos elementos se llamen "Nulo"
        series_fillna = df[col].fillna("Nulo")

        # 
        series_cont = series_fillna.value_counts()
        series_frec = series_cont/series_cont.sum()

        #
        arrays_multiindex = [[col]* len(series_cont), series_cont.index.tolist()]
        multi_index = pd.MultiIndex.from_arrays(arrays_multiindex)

        result = pd.DataFrame({"n":series_cont.values, "%": series_frec.values}, index=multi_index)
        df_frec = pd.concat([df_frec, result], axis=0)
    
    return df_frec

In [ ]:
df_frec = tabla_valores_unicos(df_copy)

In [37]:
df_frec.loc["floor"]

         n         %
Nulo  5028  0.287956
1     2689  0.154000
2     2215  0.126854
bj    1963  0.112422
3     1911  0.109444
4     1377  0.078861
5      788  0.045129
6      486  0.027833
7      294  0.016838
8      144  0.008247
en     129  0.007388
9       92  0.005269
ss      54  0.003093
10      42  0.002405
st      32  0.001833
2.0     28  0.001604
3.0     28  0.001604
-1      21  0.001203
1.0     20  0.001145
11      17  0.000974
12      17  0.000974
4.0     16  0.000916
13      14  0.000802
14      11  0.000630
6.0      9  0.000515
5.0      9  0.000515
18       3  0.000172
7.0      3  0.000172
24       3  0.000172
9.0      3  0.000172
15       2  0.000115
sm       2  0.000115
19       2  0.000115
14.0     2  0.000115
23       1  0.000057
11.0     1  0.000057
12.0     1  0.000057
24.0     1  0.000057
8.0      1  0.000057
22       1  0.000057
+1       1  0.000057

In [35]:
df_frec.loc["district"]

                               n         %
Nulo                        2429  0.139110
Centro                      2157  0.123532
Barrio de Salamanca         1544  0.088426
Chamberí                     710  0.040662
Carabanchel                  520  0.029781
...                          ...       ...
Zona Polideportivo Colonia     1  0.000057
Zona Colegios                  1  0.000057
Parque Tecnológico             1  0.000057
Parque Henares                 1  0.000057
Fuencasa                       1  0.000057

[271 rows x 2 columns]

In [41]:
df["floor"] = df["floor"].fillna("Nulo")

In [42]:
df[df["floor"]=="Nulo"]

,address,bathrooms,country,description,detailedType.subTypology,detailedType.typology,district,exterior,externalReference,floor,...,rooms,showAddress,size,status,suggestedTexts.subtitle,suggestedTexts.title,thumbnail,topNewDevelopment,topPlus,url
6,calle Transversal 1,6,es,Fantástico chalet independiente de 818 m² en f...,independantHouse,chalet,Urbanizaciones,NaN,PV8839I,Nulo,...,6,False,818.0,good,"Montealina, Pozuelo de Alarcón",Casa independiente en calle Transversal 1,https://img4.idealista.com/blur/480_360_mq/0/i...,False,True,https://www.idealista.com/inmueble/106349275/
7,calle Línea,10,es,Chalet independiente de 1.900 m² con parcela d...,independantHouse,chalet,Zona Pueblo,NaN,PV8838I,Nulo,...,7,False,1900.0,good,"Zona Pueblo, Pozuelo de Alarcón",Casa independiente en calle Línea,https://img4.idealista.com/blur/480_360_mq/0/i...,False,True,https://www.idealista.com/inmueble/106010517/
8,calle del Padre Arrupe,3,es,Gilmar Moraleja Consulting te invita descubrir...,semidetachedHouse,chalet,Encinar de los Reyes,NaN,LO-209361,Nulo,...,3,False,260.0,good,"Encinar de los Reyes, La Moraleja",Chalet pareado en calle del Padre Arrupe,https://img4.idealista.com/blur/480_360_mq/0/i...,False,True,https://www.idealista.com/inmueble/108212506/
9,paseo de la Marquesa Viuda de Aldama,11,es,GILMAR MORALEJA tiene el honor de presentar es...,independantHouse,chalet,La Moraleja urbanización,NaN,JM195047,Nulo,...,8,False,1700.0,good,"La Moraleja urbanización, La Moraleja",Casa independiente en paseo de la Marquesa Viu...,https://img4.idealista.com/blur/480_360_mq/0/i...,False,True,https://www.idealista.com/inmueble/104306965/
13,calle Eibar,10,es,Impresionante independiente de 1.600 m² sobre ...,independantHouse,chalet,Moncloa,NaN,PV8826I,Nulo,...,9,False,1674.0,good,"El Plantío, Madrid",Casa independiente en calle Eibar,https://img4.idealista.com/blur/480_360_mq/0/i...,False,True,https://www.idealista.com/inmueble/106751275/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17441,El Arroyo - La Fuente,3,es,"EXCLUSIVO CHALET RESIDENCIAL – AMPLITUD, LUZ Y...",terracedHouse,chalet,El Arroyo - La Fuente,NaN,RP1982025140496,Nulo,...,6,False,357.0,good,"El Arroyo - La Fuente, Fuenlabrada",Chalet adosado,https://img4.idealista.com/blur/480_360_mq/0/i...,False,False,https://www.idealista.com/inmueble/108913905/
17449,avenida del Monte,8,es,DS Realtors comercializa esta villa exclusiva ...,independantHouse,chalet,NaN,NaN,1-1561,Nulo,...,9,False,1403.0,renew,Santo Domingo,Casa independiente en avenida del Monte,https://img4.idealista.com/blur/480_360_mq/0/i...,False,False,https://www.idealista.com/inmueble/107551257/
17450,Barrio Fuente del Berro,3,es,Agencia inmobiliaria DS Realtors le ofrece est...,independantHouse,chalet,Barrio de Salamanca,NaN,1-1573,Nulo,...,4,False,290.0,good,"Fuente del Berro, Madrid",Casa independiente,https://img4.idealista.com/blur/480_360_mq/0/i...,False,False,https://www.idealista.com/inmueble/107795681/
17451,calle Monte Alto,5,es,"DIRECTAMENTE, ""Magníficas vistas independiente...",independantHouse,chalet,Los Peñascales,NaN,Peñascales,Nulo,...,5,False,326.0,good,"El Monte, Torrelodones",Casa independiente en calle Monte Alto,https://img4.idealista.com/blur/480_360_mq/0/i...,False,False,https://www.idealista.com/inmueble/108611539/
17457,Miramadrid,3,es,*** COMISIÓN DE AGENCIA TOTALMENTE INCLUIDA EN...,independantHouse,chalet,Miramadrid,NaN,2500501,Nulo,...,4,False,150.0,good,"Miramadrid, Paracuellos de Jarama",Casa independiente,https://img4.idealista.com/blur/480_360_mq/0/i...,False,False,https://www.idealista.com/inmueble/107283231/

# Diferenciacion de variables

## Variables con valores nulos

In [101]:
variables_nulas = list(info_types[info_types["Valores nulos"]>0].index)

# Para quitar en los siguientes puntos las columnas con nulos de las demas columnas usaremos la siguiente funcion
def remove_repeated(list1, list2):
    return [x for x in list1 if x not in list2]

In [102]:
variables_nulas

['detailedType.subTypology',
 'district',
 'exterior',
 'floor',
 'hasLift',
 'highlight.groupDescription',
 'neighborhood',
 'newDevelopmentFinished',
 'parkingSpace.hasParkingSpace',
 'parkingSpace.isParkingSpaceIncludedInPrice',
 'parkingSpace.parkingSpacePrice',
 'priceInfo.price.priceDropInfo.formerPrice',
 'priceInfo.price.priceDropInfo.priceDropPercentage',
 'priceInfo.price.priceDropInfo.priceDropValue',
 'status']

## Variables booleanas

In [103]:
# Primero vamos a analizar las variables dicotomicas, puesto que son las mas sencillas. Ademas usaremos en principio solo las 
# que no tengan valores nulos
variable_bool = info_types[info_types["Valores únicos"]<3].index.to_list()

# Una de ellas tiene valores nulos, por lo que en principio no la voy a catalogar como dicotomica
variable_bool = remove_repeated(variable_bool, variables_nulas)

In [104]:
variable_bool

['has360',
 'has3DTour',
 'hasPlan',
 'hasStaging',
 'hasVideo',
 'newDevelopment',
 'showAddress',
 'topPlus']

## Variables numericas

In [105]:
# Ahora vamos a extraer las variables numericas y ver si falta algo
variables_num = df_copy.select_dtypes(include=["number"]).columns.tolist()
variables_num = remove_repeated(variables_num, variables_nulas)
variables_num

['bathrooms',
 'numPhotos',
 'price',
 'priceByArea',
 'priceInfo.price.amount',
 'rooms',
 'size']

In [106]:
"""
for var in variables_num:
    show = df_copy.sort_values(by=var)
    print(var)
    print(show[var].head(25))
"""

'\nfor var in variables_num:\n    show = df_copy.sort_values(by=var)\n    print(var)\n    print(show[var].head(25))\n'

In [107]:
"""
var = "priceInfo.price.amount"
show = df_copy.sort_values(by=var)
comparacion = show[var] == show["price"]
print(comparacion.sum())
"""

'\nvar = "priceInfo.price.amount"\nshow = df_copy.sort_values(by=var)\ncomparacion = show[var] == show["price"]\nprint(comparacion.sum())\n'

In [ ]:
"""  
def graph_hist(series, bins="auto"):
    plt.hist(series, bins=bins)
    plt.title(series.name)
    plt.show()

for var in variables_num:
    graph_hist(df_copy[var])
"""

## Variables categoricas

In [108]:
variables_cat = df_copy.select_dtypes(include=['object', 'category']).columns.tolist()
variables_cat = remove_repeated(variables_cat, variables_nulas)
variables_cat

['detailedType.typology', 'municipality', 'propertyType']

## Sumatorio variables

In [109]:
sum_var = 0
variables = [variables_nulas, variable_bool, variables_num, variables_cat]
for var in variables:
    sum_var += len(var)
print(column_tot==sum_var)
print(f"Columnas totales: {column_tot}")
print(f"Variables: {sum_var}")

True
Columnas totales: 33
Variables: 33

# Recuperación de variables nulas

In [ ]:
"""
df_nulos = df_copy[[
    "parkingSpace.parkingSpacePrice",
    "priceInfo.price.priceDropInfo.priceDropPercentage",
    "priceInfo.price.priceDropInfo.formerPrice",
    "priceInfo.price.priceDropInfo.priceDropValue"]].notna()


def tabla_contingencia(series1, series2):
    # Creamos la tabla de contingencia
    tabla_contingencia = pd.crosstab(series1, series2)

    # Dibujamos el heatmap de la tabla de contingencia para aquellos que tengan un valor 
    # significativo de dependencia
    
    plt.figure(figsize=(8, 6))
    sns.heatmap(tabla_contingencia, annot=True, fmt='g', cmap='Blues')
    plt.title('Tabla de Contingencia Heatmap')
    plt.xlabel('Var2')
    plt.ylabel('Var1')
    plt.show()


for col in df_nulos.columns:

    series1 = df_nulos[col]
    series2 = df_copy["parkingSpace.isParkingSpaceIncludedInPrice"]

    tabla_contingencia(series1, series2)

"""

# Recuperacion de variables nulas segun los compañeros

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

In [ ]:
num_pipeline = Pipeline(steps=[
    ("num_imputer", SimpleImputer(strategy="constant", fill_value=0.0)),
    ("num_scaler", StandardScaler())
])

cat_pipeline = Pipeline(steps=[
    ("cat_imputer", SimpleImputer(strategy="constant", fill_value="Empty")),
    ("cat_encoder", OneHotEncoder())
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", num_pipeline, variables_num)
        ("cat", cat_pipeline, variables_cat)
    ]
)